package com.deepcode.springboard.admin;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface ConfigMapper {

    @Select("SELECT * FROM g5_config LIMIT 1")
    Config selectConfig();

    @Update("""
                UPDATE g5_config
                SET
                    cf_title = COALESCE(#{cfTitle}, cf_title),
                    cf_theme = COALESCE(#{cfTheme}, cf_theme),
                    cf_admin = COALESCE(#{cfAdmin}, cf_admin),
                    cf_admin_email = COALESCE(#{cfAdminEmail}, cf_admin_email),
                    cf_admin_email_name = COALESCE(#{cfAdminEmailName}, cf_admin_email_name),
                    cf_add_script = COALESCE(#{cfAddScript}, cf_add_script),
                    cf_use_point = COALESCE(#{cfUsePoint}, cf_use_point),
                    cf_point_term = COALESCE(#{cfPointTerm}, cf_point_term),
                    cf_use_copy_log = COALESCE(#{cfUseCopyLog}, cf_use_copy_log),
                    cf_use_email_certify = COALESCE(#{cfUseEmailCertify}, cf_use_email_certify),
                    cf_login_point = COALESCE(#{cfLoginPoint}, cf_login_point),
                    cf_cut_name = COALESCE(#{cfCutName}, cf_cut_name),
                    cf_nick_modify = COALESCE(#{cfNickModify}, cf_nick_modify),
                    cf_new_skin = COALESCE(#{cfNewSkin}, cf_new_skin),
                    cf_new_rows = COALESCE(#{cfNewRows}, cf_new_rows),
                    cf_search_skin = COALESCE(#{cfSearchSkin}, cf_search_skin),
                    cf_connect_skin = COALESCE(#{cfConnectSkin}, cf_connect_skin),
                    cf_faq_skin = COALESCE(#{cfFaqSkin}, cf_faq_skin),
                    cf_read_point = COALESCE(#{cfReadPoint}, cf_read_point),
                    cf_write_point = COALESCE(#{cfWritePoint}, cf_write_point),
                    cf_comment_point = COALESCE(#{cfCommentPoint}, cf_comment_point),
                    cf_download_point = COALESCE(#{cfDownloadPoint}, cf_download_point),
                    cf_write_pages = COALESCE(#{cfWritePages}, cf_write_pages),
                    cf_mobile_pages = COALESCE(#{cfMobilePages}, cf_mobile_pages),
                    cf_link_target = COALESCE(#{cfLinkTarget}, cf_link_target),
                    cf_bbs_rewrite = COALESCE(#{cfBbsRewrite}, cf_bbs_rewrite),
                    cf_delay_sec = COALESCE(#{cfDelaySec}, cf_delay_sec),
                    cf_filter = COALESCE(#{cfFilter}, cf_filter),
                    cf_possible_ip = COALESCE(#{cfPossibleIp}, cf_possible_ip),
                    cf_intercept_ip = COALESCE(#{cfInterceptIp}, cf_intercept_ip),
                    cf_analytics = COALESCE(#{cfAnalytics}, cf_analytics),
                    cf_add_meta = COALESCE(#{cfAddMeta}, cf_add_meta),
                    cf_member_skin = COALESCE(#{cfMemberSkin}, cf_member_skin),
                    cf_use_homepage = COALESCE(#{cfUseHomepage}, cf_use_homepage),
                    cf_req_homepage = COALESCE(#{cfReqHomepage}, cf_req_homepage),
                    cf_use_tel = COALESCE(#{cfUseTel}, cf_use_tel),
                    cf_req_tel = COALESCE(#{cfReqTel}, cf_req_tel),
                    cf_use_hp = COALESCE(#{cfUseHp}, cf_use_hp),
                    cf_req_hp = COALESCE(#{cfReqHp}, cf_req_hp),
                    cf_use_addr = COALESCE(#{cfUseAddr}, cf_use_addr),
                    cf_req_addr = COALESCE(#{cfReqAddr}, cf_req_addr),
                    cf_use_signature = COALESCE(#{cfUseSignature}, cf_use_signature),
                    cf_req_signature = COALESCE(#{cfReqSignature}, cf_req_signature),
                    cf_use_profile = COALESCE(#{cfUseProfile}, cf_use_profile),
                    cf_req_profile = COALESCE(#{cfReqProfile}, cf_req_profile),
                    cf_register_level = COALESCE(#{cfRegisterLevel}, cf_register_level),
                    cf_register_point = COALESCE(#{cfRegisterPoint}, cf_register_point),
                    cf_icon_level = COALESCE(#{cfIconLevel}, cf_icon_level),
                    cf_use_recommend = COALESCE(#{cfUseRecommend}, cf_use_recommend),
                    cf_recommend_point = COALESCE(#{cfRecommendPoint}, cf_recommend_point),
                    cf_leave_day = COALESCE(#{cfLeaveDay}, cf_leave_day),
                    cf_search_part = COALESCE(#{cfSearchPart}, cf_search_part),
                    cf_email_use = COALESCE(#{cfEmailUse}, cf_email_use),
                    cf_email_wr_super_admin = COALESCE(#{cfEmailWrSuperAdmin}, cf_email_wr_super_admin),
                    cf_email_wr_group_admin = COALESCE(#{cfEmailWrGroupAdmin}, cf_email_wr_group_admin),
                    cf_email_wr_board_admin = COALESCE(#{cfEmailWrBoardAdmin}, cf_email_wr_board_admin),
                    cf_email_wr_write = COALESCE(#{cfEmailWrWrite}, cf_email_wr_write),
                    cf_email_wr_comment_all = COALESCE(#{cfEmailWrCommentAll}, cf_email_wr_comment_all),
                    cf_email_mb_super_admin = COALESCE(#{cfEmailMbSuperAdmin}, cf_email_mb_super_admin),
                    cf_email_mb_member = COALESCE(#{cfEmailMbMember}, cf_email_mb_member),
                    cf_email_po_super_admin = COALESCE(#{cfEmailPoSuperAdmin}, cf_email_po_super_admin),
                    cf_prohibit_id = COALESCE(#{cfProhibitId}, cf_prohibit_id),
                    cf_prohibit_email = COALESCE(#{cfProhibitEmail}, cf_prohibit_email),
                    cf_new_del = COALESCE(#{cfNewDel}, cf_new_del),
                    cf_memo_del = COALESCE(#{cfMemoDel}, cf_memo_del),
                    cf_visit_del = COALESCE(#{cfVisitDel}, cf_visit_del),
                    cf_popular_del = COALESCE(#{cfPopularDel}, cf_popular_del),
                    cf_optimize_date = COALESCE(#{cfOptimizeDate}, cf_optimize_date),
                    cf_use_member_icon = COALESCE(#{cfUseMemberIcon}, cf_use_member_icon),
                    cf_member_icon_size = COALESCE(#{cfMemberIconSize}, cf_member_icon_size),
                    cf_member_icon_width = COALESCE(#{cfMemberIconWidth}, cf_member_icon_width),
                    cf_member_icon_height = COALESCE(#{cfMemberIconHeight}, cf_member_icon_height),
                    cf_member_img_size = COALESCE(#{cfMemberImgSize}, cf_member_img_size),
                    cf_member_img_width = COALESCE(#{cfMemberImgWidth}, cf_member_img_width),
                    cf_member_img_height = COALESCE(#{cfMemberImgHeight}, cf_member_img_height),
                    cf_login_minutes = COALESCE(#{cfLoginMinutes}, cf_login_minutes),
                    cf_image_extension = COALESCE(#{cfImageExtension}, cf_image_extension),
                    cf_flash_extension = COALESCE(#{cfFlashExtension}, cf_flash_extension),
                    cf_movie_extension = COALESCE(#{cfMovieExtension}, cf_movie_extension),
                    cf_formmail_is_member = COALESCE(#{cfFormmailIsMember}, cf_formmail_is_member),
                    cf_page_rows = COALESCE(#{cfPageRows}, cf_page_rows),
                    cf_mobile_page_rows = COALESCE(#{cfMobilePageRows}, cf_mobile_page_rows),
                    cf_visit = COALESCE(#{cfVisit}, cf_visit),
                    cf_max_po_id = COALESCE(#{cfMaxPoId}, cf_max_po_id),
                    cf_stipulation = COALESCE(#{cfStipulation}, cf_stipulation),
                    cf_privacy = COALESCE(#{cfPrivacy}, cf_privacy),
                    cf_open_modify = COALESCE(#{cfOpenModify}, cf_open_modify),
                    cf_memo_send_point = COALESCE(#{cfMemoSendPoint}, cf_memo_send_point),
                    cf_mobile_new_skin = COALESCE(#{cfMobileNewSkin}, cf_mobile_new_skin),
                    cf_mobile_search_skin = COALESCE(#{cfMobileSearchSkin}, cf_mobile_search_skin),
                    cf_mobile_connect_skin = COALESCE(#{cfMobileConnectSkin}, cf_mobile_connect_skin),
                    cf_mobile_faq_skin = COALESCE(#{cfMobileFaqSkin}, cf_mobile_faq_skin),
                    cf_mobile_member_skin = COALESCE(#{cfMobileMemberSkin}, cf_mobile_member_skin),
                    cf_captcha_mp3 = COALESCE(#{cfCaptchaMp3}, cf_captcha_mp3),
                    cf_editor = COALESCE(#{cfEditor}, cf_editor),
                    cf_cert_use = COALESCE(#{cfCertUse}, cf_cert_use),
                    cf_cert_find = COALESCE(#{cfCertFind}, cf_cert_find),
                    cf_cert_ipin = COALESCE(#{cfCertIpin}, cf_cert_ipin),
                    cf_cert_hp = COALESCE(#{cfCertHp}, cf_cert_hp),
                    cf_cert_simple = COALESCE(#{cfCertSimple}, cf_cert_simple),
                    cf_cert_kg_cd = COALESCE(#{cfCertKgCd}, cf_cert_kg_cd),
                    cf_cert_kg_mid = COALESCE(#{cfCertKgMid}, cf_cert_kg_mid),
                    cf_cert_use_seed = COALESCE(#{cfCertUseSeed}, cf_cert_use_seed),
                    cf_cert_kcb_cd = COALESCE(#{cfCertKcbCd}, cf_cert_kcb_cd),
                    cf_cert_kcp_cd = COALESCE(#{cfCertKcpCd}, cf_cert_kcp_cd),
                    cf_cert_kcp_enckey = COALESCE(#{cfCertKcpEnckey}, cf_cert_kcp_enckey),
                    cf_lg_mid = COALESCE(#{cfLgMid}, cf_lg_mid),
                    cf_lg_mert_key = COALESCE(#{cfLgMertKey}, cf_lg_mert_key),
                    cf_cert_limit = COALESCE(#{cfCertLimit}, cf_cert_limit),
                    cf_cert_req = COALESCE(#{cfCertReq}, cf_cert_req),
                    cf_sms_use = COALESCE(#{cfSmsUse}, cf_sms_use),
                    cf_sms_type = COALESCE(#{cfSmsType}, cf_sms_type),
                    cf_icode_id = COALESCE(#{cfIcodeId}, cf_icode_id),
                    cf_icode_pw = COALESCE(#{cfIcodePw}, cf_icode_pw),
                    cf_icode_server_ip = COALESCE(#{cfIcodeServerIp}, cf_icode_server_ip),
                    cf_icode_server_port = COALESCE(#{cfIcodeServerPort}, cf_icode_server_port),
                    cf_icode_token_key = COALESCE(#{cfIcodeTokenKey}, cf_icode_token_key),
                    cf_googl_shorturl_apikey = COALESCE(#{cfGooglShorturlApikey}, cf_googl_shorturl_apikey),
                    cf_social_login_use = COALESCE(#{cfSocialLoginUse}, cf_social_login_use),
                    cf_social_servicelist = COALESCE(#{cfSocialServicelist}, cf_social_servicelist),
                    cf_payco_clientid = COALESCE(#{cfPaycoClientid}, cf_payco_clientid),
                    cf_payco_secret = COALESCE(#{cfPaycoSecret}, cf_payco_secret),
                    cf_facebook_appid = COALESCE(#{cfFacebookAppid}, cf_facebook_appid),
                    cf_facebook_secret = COALESCE(#{cfFacebookSecret}, cf_facebook_secret),
                    cf_twitter_key = COALESCE(#{cfTwitterKey}, cf_twitter_key),
                    cf_twitter_secret = COALESCE(#{cfTwitterSecret}, cf_twitter_secret),
                    cf_google_clientid = COALESCE(#{cfGoogleClientid}, cf_google_clientid),
                    cf_google_secret = COALESCE(#{cfGoogleSecret}, cf_google_secret),
                    cf_naver_clientid = COALESCE(#{cfNaverClientid}, cf_naver_clientid),
                    cf_naver_secret = COALESCE(#{cfNaverSecret}, cf_naver_secret),
                    cf_kakao_rest_key = COALESCE(#{cfKakaoRestKey}, cf_kakao_rest_key),
                    cf_kakao_client_secret = COALESCE(#{cfKakaoClientSecret}, cf_kakao_client_secret),
                    cf_kakao_js_apikey = COALESCE(#{cfKakaoJsApikey}, cf_kakao_js_apikey),
                    cf_captcha = COALESCE(#{cfCaptcha}, cf_captcha),
                    cf_recaptcha_site_key = COALESCE(#{cfRecaptchaSiteKey}, cf_recaptcha_site_key),
                    cf_recaptcha_secret_key = COALESCE(#{cfRecaptchaSecretKey}, cf_recaptcha_secret_key),
                    cf_1_subj = COALESCE(#{cf1Subj}, cf_1_subj),
                    cf_2_subj = COALESCE(#{cf2Subj}, cf_2_subj),
                    cf_3_subj = COALESCE(#{cf3Subj}, cf_3_subj),
                    cf_4_subj = COALESCE(#{cf4Subj}, cf_4_subj),
                    cf_5_subj = COALESCE(#{cf5Subj}, cf_5_subj),
                    cf_6_subj = COALESCE(#{cf6Subj}, cf_6_subj),
                    cf_7_subj = COALESCE(#{cf7Subj}, cf_7_subj),
                    cf_8_subj = COALESCE(#{cf8Subj}, cf_8_subj),
                    cf_9_subj = COALESCE(#{cf9Subj}, cf_9_subj),
                    cf_10_subj = COALESCE(#{cf10Subj}, cf_10_subj),
                    cf_1 = COALESCE(#{cf1}, cf_1),
                    cf_2 = COALESCE(#{cf2}, cf_2),
                    cf_3 = COALESCE(#{cf3}, cf_3),
                    cf_4 = COALESCE(#{cf4}, cf_4),
                    cf_5 = COALESCE(#{cf5}, cf_5),
                    cf_6 = COALESCE(#{cf6}, cf_6),
                    cf_7 = COALESCE(#{cf7}, cf_7),
                    cf_8 = COALESCE(#{cf8}, cf_8),
                    cf_9 = COALESCE(#{cf9}, cf_9),
                    cf_10 = COALESCE(#{cf10}, cf_10)
                WHERE cf_id = #{cfId}
            """)
    int updateConfig(Config config);
}
