package com.gnuboard.springboard.admin;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface ConfigMapper {

    @Select("SELECT * FROM g5_config LIMIT 1")
    Config selectConfig();

    @Update("""
                UPDATE g5_config
                SET
                    cf_title = #{cfTitle},
                    cf_theme = #{cfTheme},
                    cf_admin = #{cfAdmin},
                    cf_admin_email = #{cfAdminEmail},
                    cf_admin_email_name = #{cfAdminEmailName},
                    cf_add_script = #{cfAddScript},
                    cf_use_point = #{cfUsePoint},
                    cf_point_term = #{cfPointTerm},
                    cf_use_copy_log = #{cfUseCopyLog},
                    cf_use_email_certify = #{cfUseEmailCertify},
                    cf_login_point = #{cfLoginPoint},
                    cf_cut_name = #{cfCutName},
                    cf_nick_modify = #{cfNickModify},
                    cf_new_skin = #{cfNewSkin},
                    cf_new_rows = #{cfNewRows},
                    cf_search_skin = #{cfSearchSkin},
                    cf_connect_skin = #{cfConnectSkin},
                    cf_faq_skin = #{cfFaqSkin},
                    cf_read_point = #{cfReadPoint},
                    cf_write_point = #{cfWritePoint},
                    cf_comment_point = #{cfCommentPoint},
                    cf_download_point = #{cfDownloadPoint},
                    cf_write_pages = #{cfWritePages},
                    cf_mobile_pages = #{cfMobilePages},
                    cf_link_target = #{cfLinkTarget},
                    cf_bbs_rewrite = #{cfBbsRewrite},
                    cf_delay_sec = #{cfDelaySec},
                    cf_filter = #{cfFilter},
                    cf_possible_ip = #{cfPossibleIp},
                    cf_intercept_ip = #{cfInterceptIp},
                    cf_analytics = #{cfAnalytics},
                    cf_add_meta = #{cfAddMeta},
                    cf_member_skin = #{cfMemberSkin},
                    cf_use_homepage = #{cfUseHomepage},
                    cf_req_homepage = #{cfReqHomepage},
                    cf_use_tel = #{cfUseTel},
                    cf_req_tel = #{cfReqTel},
                    cf_use_hp = #{cfUseHp},
                    cf_req_hp = #{cfReqHp},
                    cf_use_addr = #{cfUseAddr},
                    cf_req_addr = #{cfReqAddr},
                    cf_use_signature = #{cfUseSignature},
                    cf_req_signature = #{cfReqSignature},
                    cf_use_profile = #{cfUseProfile},
                    cf_req_profile = #{cfReqProfile},
                    cf_register_level = #{cfRegisterLevel},
                    cf_register_point = #{cfRegisterPoint},
                    cf_icon_level = #{cfIconLevel},
                    cf_use_recommend = #{cfUseRecommend},
                    cf_recommend_point = #{cfRecommendPoint},
                    cf_leave_day = #{cfLeaveDay},
                    cf_search_part = #{cfSearchPart},
                    cf_email_use = #{cfEmailUse},
                    cf_email_wr_super_admin = #{cfEmailWrSuperAdmin},
                    cf_email_wr_group_admin = #{cfEmailWrGroupAdmin},
                    cf_email_wr_board_admin = #{cfEmailWrBoardAdmin},
                    cf_email_wr_write = #{cfEmailWrWrite},
                    cf_email_wr_comment_all = #{cfEmailWrCommentAll},
                    cf_email_mb_super_admin = #{cfEmailMbSuperAdmin},
                    cf_email_mb_member = #{cfEmailMbMember},
                    cf_email_po_super_admin = #{cfEmailPoSuperAdmin},
                    cf_prohibit_id = #{cfProhibitId},
                    cf_prohibit_email = #{cfProhibitEmail},
                    cf_new_del = #{cfNewDel},
                    cf_memo_del = #{cfMemoDel},
                    cf_visit_del = #{cfVisitDel},
                    cf_popular_del = #{cfPopularDel},
                    cf_optimize_date = #{cfOptimizeDate},
                    cf_use_member_icon = #{cfUseMemberIcon},
                    cf_member_icon_size = #{cfMemberIconSize},
                    cf_member_icon_width = #{cfMemberIconWidth},
                    cf_member_icon_height = #{cfMemberIconHeight},
                    cf_member_img_size = #{cfMemberImgSize},
                    cf_member_img_width = #{cfMemberImgWidth},
                    cf_member_img_height = #{cfMemberImgHeight},
                    cf_login_minutes = #{cfLoginMinutes},
                    cf_image_extension = #{cfImageExtension},
                    cf_flash_extension = #{cfFlashExtension},
                    cf_movie_extension = #{cfMovieExtension},
                    cf_formmail_is_member = #{cfFormmailIsMember},
                    cf_page_rows = #{cfPageRows},
                    cf_mobile_page_rows = #{cfMobilePageRows},
                    cf_visit = #{cfVisit},
                    cf_max_po_id = #{cfMaxPoId},
                    cf_stipulation = #{cfStipulation},
                    cf_privacy = #{cfPrivacy},
                    cf_open_modify = #{cfOpenModify},
                    cf_memo_send_point = #{cfMemoSendPoint},
                    cf_mobile_new_skin = #{cfMobileNewSkin},
                    cf_mobile_search_skin = #{cfMobileSearchSkin},
                    cf_mobile_connect_skin = #{cfMobileConnectSkin},
                    cf_mobile_faq_skin = #{cfMobileFaqSkin},
                    cf_mobile_member_skin = #{cfMobileMemberSkin},
                    cf_captcha_mp3 = #{cfCaptchaMp3},
                    cf_editor = #{cfEditor},
                    cf_cert_use = #{cfCertUse},
                    cf_cert_find = #{cfCertFind},
                    cf_cert_ipin = #{cfCertIpin},
                    cf_cert_hp = #{cfCertHp},
                    cf_cert_simple = #{cfCertSimple},
                    cf_cert_kg_cd = #{cfCertKgCd},
                    cf_cert_kg_mid = #{cfCertKgMid},
                    cf_cert_use_seed = #{cfCertUseSeed},
                    cf_cert_kcb_cd = #{cfCertKcbCd},
                    cf_cert_kcp_cd = #{cfCertKcpCd},
                    cf_cert_kcp_enckey = #{cfCertKcpEnckey},
                    cf_lg_mid = #{cfLgMid},
                    cf_lg_mert_key = #{cfLgMertKey},
                    cf_cert_limit = #{cfCertLimit},
                    cf_cert_req = #{cfCertReq},
                    cf_sms_use = #{cfSmsUse},
                    cf_sms_type = #{cfSmsType},
                    cf_icode_id = #{cfIcodeId},
                    cf_icode_pw = #{cfIcodePw},
                    cf_icode_server_ip = #{cfIcodeServerIp},
                    cf_icode_server_port = #{cfIcodeServerPort},
                    cf_icode_token_key = #{cfIcodeTokenKey},
                    cf_googl_shorturl_apikey = #{cfGooglShorturlApikey},
                    cf_social_login_use = #{cfSocialLoginUse},
                    cf_social_servicelist = #{cfSocialServicelist},
                    cf_payco_clientid = #{cfPaycoClientid},
                    cf_payco_secret = #{cfPaycoSecret},
                    cf_facebook_appid = #{cfFacebookAppid},
                    cf_facebook_secret = #{cfFacebookSecret},
                    cf_twitter_key = #{cfTwitterKey},
                    cf_twitter_secret = #{cfTwitterSecret},
                    cf_google_clientid = #{cfGoogleClientid},
                    cf_google_secret = #{cfGoogleSecret},
                    cf_naver_clientid = #{cfNaverClientid},
                    cf_naver_secret = #{cfNaverSecret},
                    cf_kakao_rest_key = #{cfKakaoRestKey},
                    cf_kakao_client_secret = #{cfKakaoClientSecret},
                    cf_kakao_js_apikey = #{cfKakaoJsApikey},
                    cf_captcha = #{cfCaptcha},
                    cf_recaptcha_site_key = #{cfRecaptchaSiteKey},
                    cf_recaptcha_secret_key = #{cfRecaptchaSecretKey},
                    cf_1_subj = #{cf1Subj},
                    cf_2_subj = #{cf2Subj},
                    cf_3_subj = #{cf3Subj},
                    cf_4_subj = #{cf4Subj},
                    cf_5_subj = #{cf5Subj},
                    cf_6_subj = #{cf6Subj},
                    cf_7_subj = #{cf7Subj},
                    cf_8_subj = #{cf8Subj},
                    cf_9_subj = #{cf9Subj},
                    cf_10_subj = #{cf10Subj},
                    cf_1 = #{cf1},
                    cf_2 = #{cf2},
                    cf_3 = #{cf3},
                    cf_4 = #{cf4},
                    cf_5 = #{cf5},
                    cf_6 = #{cf6},
                    cf_7 = #{cf7},
                    cf_8 = #{cf8},
                    cf_9 = #{cf9},
                    cf_10 = #{cf10}
                WHERE cf_id = #{cfId}
            """)
    int updateConfig(Config config);
}
